conf.py:
  copyright: 2022
  project: [clickstorm] Image Point
  version: 1
  release: 1
  intersphinx_mapping:
    t3tsref:
      - http://docs.typo3.org/typo3cms/TyposcriptReference/
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  extensions:
    - sphinx.ext.intersphinx
    - t3sphinx.ext.t3extras
    - t3sphinx.ext.t3tablerows
    - t3sphinx.ext.targets
